workflow setup

diff --git a/.github/workflows/docker_database_workflow.yml b/.github/workflows/docker_database_workflow.yml
--- a/.github/workflows/docker_database_workflow.yml
+++ b/.github/workflows/docker_database_workflow.yml
@@ -25,10 +25,15 @@ jobs:
       - name: Wait for database
         run: |
           for i in {1..10}; do
-            docker exec ${{ secrets.DB_NAME }} mysql -u test -ptest 1234 -h "localhost" -P 3306 -e "SELECT 1" && break
+            if docker exec ${{ secrets.DB_NAME }} mysql -u test -ptest 1234 -h "localhost" -P 3306 -e "SELECT 1"; then
+              echo "Database is ready"
+              exit 0
+            fi
+            echo "Waiting for database to be ready..."
             sleep 5
-          done;
-        timeout: 60s  # Fail after 60 seconds if database is not ready
+          done
+          echo "Database is not ready after 50 seconds, failing..."
+          exit 1
 
       # Dump the database
       - name: Dump database
